name: boiler_app
description: Boiler monitoring dashboard for Kechez IoT platform.
publish_to: 'none'

version: 1.0.0+2
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  firebase_database: ^12.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

# Native splash screen configuration
flutter_native_splash:
  color: "#0D0D0F"

  android_12:
    color: "#0D0D0F"

# Android and iOS app icon configuration
flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true