// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxEUTlHhlQLqTNvygEIzguwJHdpezIwPI',
    appId: '1:114019282904:web:05bc9cbd4ab520f09a4cad',
    messagingSenderId: '114019282904',
    projectId: 'boiler2026-54bc8',
    authDomain: 'boiler2026-54bc8.firebaseapp.com',
    databaseURL: 'https://boiler2026-54bc8-default-rtdb.firebaseio.com',
    storageBucket: 'boiler2026-54bc8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qJeokIMlGnPE8olqtME0hGm0DiVBsBs',
    appId: '1:114019282904:android:742fa68ce943d3609a4cad',
    messagingSenderId: '114019282904',
    projectId: 'boiler2026-54bc8',
    databaseURL: 'https://boiler2026-54bc8-default-rtdb.firebaseio.com',
    storageBucket: 'boiler2026-54bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjP_W3QCO9LxgKvviWsDshBoeW2g-W_k8',
    appId: '1:114019282904:ios:1b8d0f6a1695c6189a4cad',
    messagingSenderId: '114019282904',
    projectId: 'boiler2026-54bc8',
    databaseURL: 'https://boiler2026-54bc8-default-rtdb.firebaseio.com',
    storageBucket: 'boiler2026-54bc8.firebasestorage.app',
    iosBundleId: 'com.example.boilerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjP_W3QCO9LxgKvviWsDshBoeW2g-W_k8',
    appId: '1:114019282904:ios:1b8d0f6a1695c6189a4cad',
    messagingSenderId: '114019282904',
    projectId: 'boiler2026-54bc8',
    databaseURL: 'https://boiler2026-54bc8-default-rtdb.firebaseio.com',
    storageBucket: 'boiler2026-54bc8.firebasestorage.app',
    iosBundleId: 'com.example.boilerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxEUTlHhlQLqTNvygEIzguwJHdpezIwPI',
    appId: '1:114019282904:web:8e7a60e4f463b2459a4cad',
    messagingSenderId: '114019282904',
    projectId: 'boiler2026-54bc8',
    authDomain: 'boiler2026-54bc8.firebaseapp.com',
    databaseURL: 'https://boiler2026-54bc8-default-rtdb.firebaseio.com',
    storageBucket: 'boiler2026-54bc8.firebasestorage.app',
  );
}
