import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'auth/auth_service.dart';
import 'cloud/firebase_connection_manager.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` -- see README
import 'screens/home_screen.dart';
import 'screens/splash_screen.dart';
import 'state/device_store.dart';
import 'theme/app_colors.dart';
import 'theme/theme_store.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const BoilerApp());
}

class BoilerApp extends StatefulWidget {
  const BoilerApp({super.key});

  @override
  State<BoilerApp> createState() => _BoilerAppState();
}

class _BoilerAppState extends State<BoilerApp> {
  final DeviceStore _store = DeviceStore();
  final ThemeStore _themeStore = ThemeStore();
  final AuthService _auth = AuthService();
  FirebaseConnectionManager? _cloudManager;
  StreamSubscription<User?>? _authSub;
  User? _user;
  String? _connectError; // set when the silent sign-in failed (e.g. no internet at first launch)
  bool _ready = false;
  bool _retrying = false;

  @override
  void initState() {
    super.initState();
    _bootstrap();
  }

  Future<void> _bootstrap() async {
    await _themeStore.load();
    // Listeners are created per boiler as soon as this phone's boiler list
    // loads, and stay in sync as boilers are added or removed.
    _cloudManager = FirebaseConnectionManager(_store);

    _authSub = _auth.authChanges.listen(_onUser);
    final error = await _auth.ensureSignedIn();
    if (error != null) _connectError = error;

    // Splash's own draw-in animation runs ~2000ms -- hold at least that long
    // so it isn't cut short by a fast start.
    await Future.delayed(const Duration(milliseconds: 2100));

    if (mounted) setState(() => _ready = true);
  }

  void _onUser(User? user) {
    _user = user;
    if (user == null) {
      _store.detach();
    } else {
      _connectError = null;
      _store.attach(user.uid);
    }
    if (mounted) setState(() {});
  }

  Future<void> _retry() async {
    setState(() => _retrying = true);
    final error = await _auth.ensureSignedIn();
    if (!mounted) return;
    setState(() {
      _retrying = false;
      _connectError = error;
    });
  }

  @override
  void dispose() {
    _authSub?.cancel();
    _cloudManager?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final Widget home;
    if (!_ready) {
      home = const SplashScreen();
    } else if (_user == null) {
      home = _ConnectScreen(
        themeStore: _themeStore,
        message: _connectError ?? 'Connecting...',
        busy: _retrying,
        onRetry: _retry,
      );
    } else {
      home = HomeScreen(store: _store, themeStore: _themeStore);
    }
    return MaterialApp(
      title: 'Boiler monitor',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(),
      home: home,
    );
  }
}

/// Shown only if the app could not reach the cloud at all on startup.
class _ConnectScreen extends StatelessWidget {
  final ThemeStore themeStore;
  final String message;
  final bool busy;
  final VoidCallback onRetry;

  const _ConnectScreen({
    required this.themeStore,
    required this.message,
    required this.busy,
    required this.onRetry,
  });

  @override
  Widget build(BuildContext context) {
    return ListenableBuilder(
      listenable: themeStore,
      builder: (context, _) {
        final AppColors colors = themeStore.colors;
        return Scaffold(
          backgroundColor: colors.background,
          body: Center(
            child: Padding(
              padding: const EdgeInsets.all(32),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(Icons.cloud_off, size: 48, color: colors.textSecondary),
                  const SizedBox(height: 16),
                  Text(message, textAlign: TextAlign.center, style: TextStyle(color: colors.textPrimary)),
                  const SizedBox(height: 20),
                  ElevatedButton(
                    onPressed: busy ? null : onRetry,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: colors.accent,
                      foregroundColor: colors.onAccent,
                    ),
                    child: busy
                        ? SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(strokeWidth: 2, color: colors.onAccent),
                          )
                        : const Text('Try again'),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}
